export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Find } from './Find'
export { default as Form } from './Form'
export { default as Gallery } from './Gallery'